"use client";

import { useState, type ChangeEvent } from "react";

interface Preset {
  name: string;
  h: number;
}

type Unit = "g" | "cup";

const PRESETS: Preset[] = [
  { name: "Bagel (65%)", h: 65 },
  { name: "Sandwich (70%)", h: 70 },
  { name: "Classic (75%)", h: 75 },
  { name: "Country (80%)", h: 80 },
  { name: "Open Crumb (85%)", h: 85 },
  { name: "Ciabatta (100%)", h: 100 },
];

// grams per 1 US cup (King Arthur standard)
const CUP_GRAMS: Record<"flour" | "water" | "salt" | "starter", number> = {
  flour: 120,
  water: 240,
  salt: 273,   // cup of salt is unusual; tsp = 6g shown when unit=cup
  starter: 240,
};

function fmt(n: number, kind: "flour" | "water" | "salt" | "starter", unit: Unit): string {
  if (unit === "g") {
    if (n >= 1000) return (n / 1000).toFixed(2) + " kg";
    return n.toFixed(1) + " g";
  }
  // cup mode: salt -> tsp, others -> cup
  if (kind === "salt") {
    const tsp = n / 6;
    if (tsp >= 1) return tsp.toFixed(1) + " tsp";
    return (tsp * 3).toFixed(1) + " dash";
  }
  const cups = n / CUP_GRAMS[kind];
  if (cups >= 1) return cups.toFixed(2) + " cup" + (cups >= 2 ? "s" : "");
  // small amounts -> tablespoons
  return (cups * 16).toFixed(1) + " tbsp";
}

function fmtSimpleGrams(n: number, unit: Unit): string {
  if (unit === "g") {
    if (n >= 1000) return (n / 1000).toFixed(2) + " kg";
    return n.toFixed(0) + " g";
  }
  // fallback for totalDough
  return (n / 1000).toFixed(2) + " kg";
}

export default function Calculator(): JSX.Element {
  const [flour, setFlour] = useState<number>(500);
  const [hydration, setHydration] = useState<number>(75);
  const [salt, setSalt] = useState<number>(2);
  const [starter, setStarter] = useState<number>(20);
  const [unit, setUnit] = useState<Unit>("g");
  const [copied, setCopied] = useState<boolean>(false);

  const water = flour * (hydration / 100);
  const saltGrams = flour * (salt / 100);
  const totalStarter = flour * (starter / 100);
  const starterFlour = totalStarter * 0.5;
  const starterWater = totalStarter * 0.5;
  const flourToAdd = flour - starterFlour;
  const waterToAdd = water - starterWater;
  const totalDough = flourToAdd + waterToAdd + saltGrams + totalStarter;

  const applyPreset = (h: number): void => {
    setHydration(h);
  };

  const onNumber = (setter: (n: number) => void) =>
    (e: ChangeEvent<HTMLInputElement>): void => setter(parseFloat(e.target.value) || 0);

  const handlePrint = (): void => {
    if (typeof window !== "undefined") window.print();
  };

  const handleCopy = async (): Promise<void> => {
    const lines = [
      "Sourdough Recipe",
      "",
      `Flour (total):         ${flour.toFixed(0)} g`,
      `Hydration:            ${hydration.toFixed(0)} %`,
      `Salt:                 ${saltGrams.toFixed(1)} g  (${(salt).toFixed(1)} % of flour)`,
      `Starter (total):      ${totalStarter.toFixed(0)} g  (${(starter).toFixed(0)} % of flour)`,
      "",
      "To add:",
      `  Flour:              ${flourToAdd.toFixed(0)} g  (excl. ${starterFlour.toFixed(0)} g in starter)`,
      `  Water:              ${waterToAdd.toFixed(0)} g  (incl. ${starterWater.toFixed(0)} g in starter, total ${water.toFixed(0)} g)`,
      `  Salt:               ${saltGrams.toFixed(1)} g`,
      `  Starter:            ${totalStarter.toFixed(0)} g`,
      "",
      `Total dough weight:   ${totalDough.toFixed(0)} g  (${fmtSimpleGrams(totalDough, "g")})`,
      "",
      `Generated by SourdoughCalc (sourdough-hydrationcalculator.com)`,
    ];
    const text = lines.join("\n");
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // fallback for older browsers
      const ta = document.createElement("textarea");
      ta.value = text;
      document.body.appendChild(ta);
      ta.select();
      document.execCommand("copy");
      document.body.removeChild(ta);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  return (
    <div className="bg-white rounded-2xl shadow-lg shadow-brand-brown/10 p-8 max-w-3xl mx-auto print:shadow-none print:p-0 print:rounded-none">
      <div className="flex items-center justify-between mb-8 flex-wrap gap-3 print:justify-start">
        <h2 className="text-center text-[25px] flex-1">馃 Calculate Your Recipe</h2>
        <div className="flex gap-1 text-xs print:hidden">
          <button
            type="button"
            onClick={() => setUnit("g")}
            className={
              "px-3 py-1.5 rounded-md font-medium border transition-colors " +
              (unit === "g"
                ? "bg-brand-brown text-white border-brand-brown"
                : "bg-white text-brand-dark border-[#E8DDC8] hover:border-brand-brown")
            }
            aria-pressed={unit === "g"}
          >
            Grams (g)
          </button>
          <button
            type="button"
            onClick={() => setUnit("cup")}
            className={
              "px-3 py-1.5 rounded-md font-medium border transition-colors " +
              (unit === "cup"
                ? "bg-brand-brown text-white border-brand-brown"
                : "bg-white text-brand-dark border-[#E8DDC8] hover:border-brand-brown")
            }
            aria-pressed={unit === "cup"}
          >
            Cups / tsp
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-5 mb-7">

        <div className="flex flex-col">
          <label className="font-semibold mb-1.5 text-brand-dark">Flour Weight (g)</label>
          <input
            type="number"
            value={flour}
            onChange={onNumber(setFlour)}
            min="1"
            className="px-3.5 py-3 border-2 border-[#E8DDC8] rounded-lg text-base focus:outline-none focus:border-brand-brown"
          />
        </div>

        <div className="flex flex-col">
          <label className="font-semibold mb-1.5 text-brand-dark">Hydration (%)</label>
          <input
            type="number"
            value={hydration}
            onChange={onNumber(setHydration)}
            min="50"
            max="150"
            className="px-3.5 py-3 border-2 border-[#E8DDC8] rounded-lg text-base focus:outline-none focus:border-brand-brown"
          />
          <small className="text-brand-muted text-sm mt-1">Beginner: 70% 路 Classic: 75% 路 Open crumb: 85%</small>
        </div>

        <div className="flex flex-col">
          <label className="font-semibold mb-1.5 text-brand-dark">Salt (%)</label>
          <input
            type="number"
            value={salt}
            onChange={onNumber(setSalt)}
            min="0"
            max="5"
            step="0.1"
            className="px-3.5 py-3 border-2 border-[#E8DDC8] rounded-lg text-base focus:outline-none focus:border-brand-brown"
          />
          <small className="text-brand-muted text-sm mt-1">Standard: 2%</small>
        </div>

        <div className="flex flex-col">
          <label className="font-semibold mb-1.5 text-brand-dark">Starter (% of flour)</label>
          <input
            type="number"
            value={starter}
            onChange={onNumber(setStarter)}
            min="0"
            max="50"
            className="px-3.5 py-3 border-2 border-[#E8DDC8] rounded-lg text-base focus:outline-none focus:border-brand-brown"
          />
          <small className="text-brand-muted text-sm mt-1">Standard: 20%</small>
        </div>
      </div>

      <div className="mt-8 pt-8 border-t border-[#E8DDC8]">
        <h3 className="text-center text-brand-brown text-[25px] mb-6">Your Recipe</h3>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
          <div className="flex items-center gap-3 px-4 py-3.5 bg-brand-cream rounded-lg">
            <span className="text-2xl">馃拑</span>
            <div>
              <div className="text-xs text-brand-muted font-medium">Water to Add</div>
              <div className="text-xl font-bold text-brand-dark">{fmt(waterToAdd, "water", unit)}</div>
              <div className="text-[10px] text-brand-muted mt-0.5">total {fmt(water, "water", unit)} incl. starter</div>
            </div>
          </div>

          <div className="flex items-center gap-3 px-4 py-3.5 bg-brand-cream rounded-lg">
            <span className="text-2xl">馃徚</span>
            <div>
              <div className="text-xs text-brand-muted font-medium">Salt</div>
              <div className="text-xl font-bold text-brand-dark">{fmt(saltGrams, "salt", unit)}</div>
            </div>
          </div>

          <div className="flex items-center gap-3 px-4 py-3.5 bg-brand-cream rounded-lg">
            <span className="text-2xl">馃尦</span>
            <div>
              <div className="text-xs text-brand-muted font-medium">Flour to Add</div>
              <div className="text-xl font-bold text-brand-dark">{fmt(flourToAdd, "flour", unit)}</div>
              <div className="text-[10px] text-brand-muted mt-0.5">excl. {fmt(starterFlour, "flour", unit)} in starter</div>
            </div>
          </div>

          <div className="flex items-center gap-3 px-4 py-3.5 bg-brand-cream rounded-lg">
            <span className="text-2xl">馃尯</span>
            <div>
              <div className="text-xs text-brand-muted font-medium">Total Starter</div>
              <div className="text-xl font-bold text-brand-dark">{fmt(totalStarter, "starter", unit)}</div>
            </div>
          </div>

          <div className="flex items-center gap-3 px-4 py-3.5 bg-brand-tan rounded-lg">
            <span className="text-2xl">馃</span>
            <div>
              <div className="text-xs text-brand-muted font-medium">Starter Flour</div>
              <div className="text-xl font-bold text-brand-dark">{fmt(starterFlour, "flour", unit)}</div>
            </div>
          </div>

          <div className="flex items-center gap-3 px-4 py-3.5 bg-brand-tan rounded-lg">
            <span className="text-2xl">馃</span>
            <div>
              <div className="text-xs text-brand-muted font-medium">Starter Water</div>
              <div className="text-xl font-bold text-brand-dark">{fmt(starterWater, "water", unit)}</div>
            </div>
          </div>

          <div className="flex items-center gap-3 px-4 py-3.5 bg-brand-brown text-white rounded-lg md:col-span-2">
            <div>
              <div className="text-xs text-white/80 font-medium">Total Dough Weight</div>
              <div className="text-xl font-bold">{fmtSimpleGrams(totalDough, unit)}</div>
            </div>
          </div>
        </div>

        <div className="flex justify-center gap-3 mt-4 print:hidden">
          <button
            type="button"
            onClick={handlePrint}
            className="px-5 py-2.5 bg-brand-wheat text-brand-dark rounded-md font-semibold hover:bg-brand-wheat-dark transition-colors"
          >
            馃勦馃嵁 Print Recipe
          </button>
          <button
            type="button"
            onClick={handleCopy}
            className="px-5 py-2.5 bg-white text-brand-brown border-2 border-brand-brown rounded-md font-semibold hover:bg-brand-brown hover:text-white transition-colors"
          >
            {copied ? "馃帀 Copied!" : "馃抄 Copy Recipe"}
          </button>
        </div>

        <div className="text-center pt-4 border-t border-dashed border-[#E8DDC8] mt-6">
          <p className="text-brand-muted text-[25px] mb-3">Try a preset:</p>
          <div className="flex flex-wrap justify-center gap-2">
            {PRESETS.map((p) => (
              <button
                key={p.h}
                onClick={() => applyPreset(p.h)}
                className="px-3.5 py-2 bg-white text-brand-brown border-[1.5px] border-brand-brown rounded-md text-sm font-medium hover:bg-brand-brown hover:text-white transition-colors"
              >
                {p.name}
              </button>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}